quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=restaurante_user
quarkus.datasource.password=restaurante_pass
quarkus.datasource.jdbc.url=jdbc:postgresql://127.0.0.1:5432/restaurante_pos
quarkus.http.port=8080
# Liquibase minimal config properties
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/db.changelog-master.sql