quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=restaurante_user
quarkus.datasource.password=restaurante_pass
quarkus.datasource.jdbc.url=jdbc:postgresql://127.0.0.1:5432/restaurante_pos
quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.enabled=true
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.exposed-headers=X-Paging-Total-Count,X-Paging-Current-Page

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Restaurante POS API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API para gerenciamento de ponto de venda de restaurante.

# Liquibase minimal config properties
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/db.changelog-master.sql
